api/urls.py
from django.urls import path
from .views import ClienteList, GastoConductorList, GastoConductorAPIList, gastoConductorListReload, gastoConductorList

urlpatterns = [
    path('v1/clientes',ClienteList.as_view(),name='cliente_list'),
    # path('v1/gastos',GastoConductorAPIList.as_view(),name='gastos_list'),
    # path('v1/gastos/reload/view',GastoConductorList.as_view(),name='gastos_list_reload_view'),
    # path('v1/gastos/reload/',gastoConductorList,name='gastos_list_reload'),
    path('v1/gastos/reload/',gastoConductorListReload,name='gastos_list_reload'),
    # path('v1/gastos/reload/(?:fecha=(?P<str:fecha>)/)?$',gastoConductorListReload,name='gastos_list_reload_f'),
    # path('v1/gastos/reload/(?:page-(?P<page_number>[0-9]+)/)?$',gastoConductorListReload,name='gastos_list_reload'),
]

app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('',include(('bases.urls','bases'), namespace='bases')),
    path('elim/',include(('elim.urls','elim'), namespace='elim')),
    path('api/', include(('api.urls', 'api'), namespace='api')),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('admin/', admin.site.urls),
    path('viviana/',include(('viviana.urls','viviana'), namespace='viviana')),
]

urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

elim/urls.py
from rest_framework.routers import DefaultRouter
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

#from .views import *
from . import views
from .reportes import reporte_registros


urlpatterns = [
    path('clientes/',views.ClienteView.as_view(), name='cliente_list'),
    path('clientes/new/',views.ClienteNew.as_view(), name='cliente_new'),
    path('clientes/edit/<int:pk>',views.ClienteEdit.as_view(), name='cliente_edit'),
    path('clientes/inactivar/<int:id>',views.cliente_inactivar, name='cliente_inactivar'),
    path('clientes/delete/<int:pk>',views.ClienteDel.as_view(), name='cliente_del'),

    path('vehiculos/',views.VehiculoView.as_view(), name='vehiculo_list'),
    path('vehiculos/new/',views.VehiculoNew.as_view(), name='vehiculo_new'),
    path('vehiculos/edit/<str:pk>',views.VehiculoEdit.as_view(), name='vehiculo_edit'),
    path('vehiculos/inactivar/<str:pk>',views.vehiculo_inactivar, name='vehiculo_inactivar'),


    path('proveedores/',views.ProveedorView.as_view(), name='proveedor_list'),
    path('proveedores/new',views.ProveedorNew.as_view(), name='proveedor_new'),
    path('proveedores/edit/<int:pk>',views.ProveedorEdit.as_view(), name='proveedor_edit'),
    path('proveedores/delete/<int:pk>',views.ProveedorDel.as_view(), name='proveedor_del'),
    
    path('conductor/',views.ConductorView.as_view(), name='conductor_view'),
    path('conductor/edit/<str:pk>',views.ConductorEdit.as_view(), name='conductor_edit'),
    
    # path('servicios/',ServicioView.as_view(), name='servicio_list'),
    # path('servicios/new',ServicioNew.as_view(), name='servicio_new'),
    # path('servicios/edit/<int:pk>',ServicioEdit.as_view(), name='servicio_edit'),
    # path('servicios/delete/<int:pk>',ServicioDel.as_view(), name='servicio_del'),

    # path('servicios/o',servicio_new, name='servicio_def'),

    # path('servicios/u',MuseoCreateView.as_view(), name='museo-add'),


    path('registros/',views.RegistroView.as_view(), name='reg_list'),
    # path('registros/new',views.RegistroNew.as_view(), name='reg_new'),
    # path('registros/edit/<int:pk>',views.RegistroEdit.as_view(), name='reg_edit'),
    path('registros/new',views.reg_add_edit, name='reg_new'),
    path('registros/edit/<int:id>',views.reg_add_edit, name='reg_edit'),
    # path('registros/inactivar/<int:id>',views.cliente_inactivar, name="cliente_inactivar"),

    path('registros/lista/direccion/',views.TrayectoView.as_view(), name='reg_direccion_new'),
    path('registros/direccion/new/',views.TrayectoNew.as_view(), name='reg_direccion_add_new'),

    path('prueba/', views.index, name="index"),
    path('js', views.index_js, name="index-js"),
    path('localizacion', views.localizacion, name="local"),
    
    
    path('trayectos/', views.HomeTrayectosView.as_view(), name='trayecto_view'), 
    path('trayectos/<int:pk>', views.ActInaTrayectoView.as_view(), name='actina_view'), 
    path('rutas/', views.rutas, name="route"),
    path('geocoding/<int:pk>', views.GeocodingView.as_view(), name='geocoding_view'),     
    path('distance', views.DistanceView.as_view(), name='my_distance_view'), 
    

    path('gastos/',views.GastoConductorView.as_view(), name='gasto_list'),
    # path('gastos/',views.gastoConductorView, name='gasto_list'),
    path('gastos/new/',views.GastoConductorNew.as_view(), name='gasto_new'),
    path('gastos/edit/<int:pk>',views.GastoConductorEdit.as_view(), name='gasto_edit'),
    path('gastos/detail/<int:pk>',views.GastoConductorDetailView.as_view(), name='gasto_detail'),
    
    path('map/', views.MapView.as_view(), name='my_map_view'), 
    path('map/conductor/', views.MapConductorView.as_view(), name='conductor_map_view'), 
    path('route/', views.route, name="route"),

    path('reporte/', reporte_registros, name='registros_print_all'),
    
    path('reporte/list/',views.ReporteView.as_view(), name='repo_list'),    
    path('reporte/detail/<int:pk>',views.ReporteDetailView.as_view(), name='repo_detail'),
    
    path('conductor/viaje/reporte/list/',views.ViajeView.as_view(), name='repo_viaje_list'),    
    path('conductor/viaje/reporte/detail/<int:pk>',views.ViajeDetailView.as_view(), name='repo_viaje_detail'),
    
    path('status/',views.StatusDetailView.as_view(), name='status_list'),
    path('status/<str:pk>/',views.vehiculo_activar_inactivar, name='status_activarinact_list'),
    # path('status/<str:pk>/(?:page(?P<page_number>[0-9]+)/)?$',views.vehiculo_activar_inactivar, name='status_activarinact_list'),
    path('status/mecanico/<str:pk>/',views.vehiculo_cambiar_mecanico, name='status_cambiar_mecanico_list'),
    path('status/restaurante/<str:pk>/',views.vehiculo_cambiar_restaurante, name='status_cambiar_restaurante_list'),
    path('status/enfermo/<str:pk>/',views.vehiculo_cambiar_enfermo, name='status_cambiar_enfermo_list'),
    path('status/color/<str:pk>/',views.vehiculo_status_disponibilidad, name='status_cambiar_color_list'),
    path('status/edit/<str:pk>/',views.StatusEdit.as_view(), name='status_edit'),
    
    path('panel/',views.panelView, name='panel_view'),
]


router = DefaultRouter()
router.register("api/paises", views.PaisesViewSet, basename="paises")
router.register("api/museos", views.MuseoViewSet, basename="museos_list")
router.register("api/clientes", views.ClientesViewSet, basename="clientes")
router.register("v1/clientes/", views.ClientesViewSet, basename="clientes_list")
# router.register("v1/gastos", views.GastoConductorViewSet, basename="gastos__list")

urlpatterns += router.urls
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

elim/views.py
from multiprocessing.managers import BaseManager
from django.shortcuts import get_object_or_404,render, redirect
from django.contrib.auth.models import User
from django.views import generic
from django.urls import reverse_lazy
from django.http import HttpResponse, HttpResponseRedirect
from rest_framework import viewsets, filters
from django_filters.rest_framework import  DjangoFilterBackend
from django_filters import rest_framework as filters2
from django.http import JsonResponse
from django.template.loader import get_template
from xhtml2pdf import pisa
from django.utils import timezone
from django.db.models import Sum, Count,FloatField, IntegerField, CharField, F
from django.db.models.functions import Cast, Coalesce


from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.decorators import login_required, permission_required

from bases.views import SinPrivilegios
from django.views import View
from datetime import datetime
from django.conf import settings
from django.db.models import Case, Value, When

from django.core.paginator import Paginator
from django.urls import reverse

import json
import requests
import googlemaps
import os


from .models import Cliente, GastoConductor,Proveedor,Servicio,Vehiculo \
    ,Programador,Trayecto,Persona,Museo, Pais, Registro \
        , Locations,Distances,PerfilConductor , Viaje
from .forms import ClienteForm,ProveedorForm,\
                ServicioForm, MuseoForm , RegistroForm,\
                DistanceForm, TrayectoForm, VehiculoForm,ConductorForm , GastoConductorForm ,\
                    ViajeConductorForm, GastoConductorFormFilter, PanelForm

from .serializers import MuseoSerializer, PaisSerializer,ClienteSerializer,GastoConductorSerializer 
from .filterset import GastoConductorFilter

# Create your views base.

class VistaBaseCreate(SuccessMessageMixin,SinPrivilegios, generic.CreateView):
    context_object_name = 'obj'
    success_message="Registro agregado satisfactoriamente"

    def form_valid(self, form):
        form.instance.uc = self.request.user
        return super().form_valid(form)

class VistaBaseEdit(SuccessMessageMixin,SinPrivilegios, generic.UpdateView):
    context_object_name = 'obj'
    success_message="Registro actualizado satisfactoriamente"
    
    def form_valid(self, form):
        form.instance.um = self.request.user.id
        return super().form_valid(form) 


# Bloque views cliente.

class ClienteView(SinPrivilegios, generic.ListView):
    permission_required = "elim.view_cliente"
    model = Cliente
    template_name = "elim/cliente_list.html"
    context_object_name = "obj"
    ordering = ['nombre']

class ClienteNew(VistaBaseCreate):
    model = Cliente
    template_name="elim/cliente_form.html"
    context_object_name = "obj"
    form_class=ClienteForm
    success_url=reverse_lazy("elim:cliente_list")
    success_message="Cliente creado satisfactoriamente"
    permission_required="elim.add_cliente"    

class ClienteEdit(VistaBaseEdit):
    permission_required="elim.change_cliente"
    model = Cliente
    template_name = "elim/cliente_form.html"
    context_object_name = "obj"
    form_class = ClienteForm
    success_url = reverse_lazy("elim:cliente_list")
    success_message = "Cliente actualizado satisfactoriamente"

class ClienteDel(SuccessMessageMixin, SinPrivilegios, generic.DeleteView):
    permission_required="elim.delete_cliente"
    model = Cliente
    template_name ='elim/cliente_del.html'
    context_object_name ='obj'
    success_url = reverse_lazy("elim:cliente_list")
    success_message="Cliente eliminado satisfactoriamente"


@login_required(login_url="/login/")
@permission_required("elim.change_cliente",login_url="/login/")
def cliente_inactivar(request,id): 
    if cliente:=Cliente.objects.filter(pk=id).first():
        cliente.estado = not cliente.estado
        cliente.save()
        return redirect('elim:cliente_list')    
    return HttpResponse("FAIL")

# Bloque views Conductor.

class ConductorView(SinPrivilegios, generic.ListView):
    permission_required = "elim.change_vehiculo"
    model = Vehiculo
    template_name = "conductor/conductor_list.html"
    context_object_name = "obj"
    
  
    def get_queryset(self):                
        if PerfilConductor.objects.filter(usuario = self.request.user):                 
            return super().get_queryset().filter(placa=PerfilConductor.objects.get(usuario = self.request.user))
    
    def get_context_data(self, **kwargs):
        
        print('self.kwargs',self.kwargs)
        
        ip = requests.get('https://api.ipify.org?format=json')
        ip_data = json.loads(ip.text)
        print(ip_data)
        res = requests.get('http://ip-api.com/json/'+ip_data['ip'])
        location_data_one = res.text
        location_data = json.loads(location_data_one)
        print(location_data)
        print(location_data['lon'])
        # print(location_data.lat)
        
        
        context = super().get_context_data(**kwargs)
        print('*-*-*-',context)
        obj=  context["obj"] 
        obj.lat = location_data['lat']
        obj.lng = location_data['lon']
        print('*-*-*-',obj[0] )
        print('*-*-*-',obj.lat)
        print('*-*-*-',obj.lng)
        # print('*-*-*-',obj.id)
        
        ubicacion = Vehiculo.objects.get(pk=obj[0]).ubicacion.id 
        print('ubicacion',ubicacion)
        if ubicacion:
            # Trayecto.objects.get(pk=placa)            
            location = Trayecto.objects.get(pk=ubicacion) 
        
            print(location)
            if not location.lat and not location.lng:
                print('nul')
        
            # if location.direccion and location.ciudad and location.zipcode and location.ciudad != None: 
            #     direccion_string = str(location.direccion)+", "+str(location.zipcode)+", "+str(location.ciudad)+", "+str(location.pais)

            #     gmaps = googlemaps.Client(key = settings.GOOGLE_API_KEY)
            #     result = gmaps.geocode(direccion_string)[0]
                
            #     location.lat = result.get('geometry', {}).get('location', {}).get('lat', None)
            #     location.lng = result.get('geometry', {}).get('location', {}).get('lng', None)
            #     location.place_id = result.get('place_id', {})
            #     # location.um = self.request.user.id
            #     location.save()
            
            # return redirect('elim:trayecto_view')
        return context

class ConductorEdit(VistaBaseEdit):
    permission_required = "elim.change_vehiculo"
    model = Vehiculo
    template_name = "conductor/conductor_form.html"
    context_object_name = "obj"
    form_class = ConductorForm
    success_url = reverse_lazy("elim:conductor_view")
    success_message = "Conductor actualizado satisfactoriamente"
    
    def form_valid(self, form):
        form.instance.um = self.request.user.id
        # form.instance.direccion = str(form.instance.direccion).strip()
        return super().form_valid(form)

# Bloque views Trayecto.
class TrayectoView(SinPrivilegios, generic.ListView):
    permission_required = "elim.view_trayecto"
    model = Trayecto
    template_name = "trayectos/trayecto_list.html"
    context_object_name = "obj"
    ordering = ['-id']

class TrayectoNew(VistaBaseCreate):
    model=Trayecto
    template_name="trayectos/trayecto_form.html"
    context_object_name="obj"
    form_class=TrayectoForm
    success_url=reverse_lazy("elim:reg_list")
    success_message="Trayecto creado satisfactoriamente"
    permission_required="elim.add_trayecto"
    
    def form_valid(self, form):
        form.instance.uc = self.request.user
        form.instance.direccion = str(form.instance.direccion).strip()
        return super().form_valid(form)
    
    
class TrayectoEdit(VistaBaseEdit):
    permission_required="elim.change_trayecto"
    model = Trayecto
    template_name = "trayecto/trayecto_form.html"
    context_object_name = "obj"
    form_class = TrayectoForm
    success_url = reverse_lazy("elim:reg_direccion_new")
    success_message = "Trayecto actualizado satisfactoriamente"
    
    def form_valid(self, form):
        form.instance.um = self.request.user.id
        form.instance.direccion = str(form.instance.direccion).strip()
        return super().form_valid(form)

@login_required(login_url="/login/")
@permission_required("elim.change_trayecto",login_url="/login/")
def direccion_inactivar(request,id):    
    if reg:= Trayecto.objects.filter(pk=id).first():
        reg.estado = not reg.estado
        reg.save()
        return redirect('elim:trayecto_list')   
    return HttpResponse("FAIL")


# Bloque views Vehiculo.

class VehiculoView(SinPrivilegios, generic.ListView):
    permission_required = "elim.view_vehiculo"
    model = Vehiculo
    template_name = "vehiculos/vehiculo_list.html"
    context_object_name = "obj"
    ordering = ['placa','conductor']

class VehiculoNew(VistaBaseCreate):
    model=Vehiculo
    template_name="vehiculos/vehiculo_form.html"
    context_object_name="obj"
    form_class=VehiculoForm
    success_url=reverse_lazy("elim:vehiculo_list")
    success_message="Vehiculo creado satisfactoriamente"
    permission_required="elim.add_vehiculo" 

class VehiculoEdit(VistaBaseEdit):
    permission_required="elim.change_vehiculo"
    model = Vehiculo
    template_name = "vehiculos/vehiculo_form.html"
    context_object_name = "obj"
    form_class = VehiculoForm
    success_url = reverse_lazy("elim:vehiculo_list")
    success_message = "Vehiculo actualizado satisfactoriamente"
    
    def form_valid(self, form):
        # form.instance.uc = self.request.user
        return super().form_valid(form)


@login_required(login_url="/login/")
@permission_required("elim.change_vehiculo",login_url="/login/")
def vehiculo_status_disponibilidad(request,pk):
    fecha = request.GET.get('fecha')
    page = request.GET.get('page')

elim/templates/conductor/viajes/repo_detail.html
{% load static %}
<div class="modal-dialog modal-xl">
    <div class="modal-content">
        <div class="modal-header">
            <h4 class="modal-title">Reporte, {{obj.from_location}} <span> </span></h4>
            <button type="button" class="close" onclick="return cerrar_modal()">&times;</button>
        </div>
        <div class="modal-body">
        </div>
        <div class="modal-footer">
            <button onclick="return cerrar_modal()" type="button" class="btn btn-success"
                data-dismiss="modal">Cerrrar</button>
        </div>
    </div>
</div>


{% block js_page %}

<script>
</script>

{% endblock %}

elim/templates/conductor/viajes/repo_list.html
{% extends 'base/base.html' %}
{% block page_content %}
{% load humanize %}
<div class="card shadow mb-4">
    <!-- Card Header - Dropdown -->
    <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
        <h6 class="m-0 font-weight-bold text-primary">Reporte</h6>
        <div class="dropdown no-arrow">
            
            <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown"
                aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
            </a>
            <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in" aria-labelledby="dropdownMenuLink">
                <div class="dropdown-header">Acciones:</div>
                <a class="dropdown-item" href="{% url 'elim:gasto_new' %}">
                    <i class="far fa-calendar-plus"></i> Nuevo</a>
            </div>
        </div>
    </div>
    <!-- Card Body -->
    <div class="card-body">
        <!-- <div class="titleholder"> -->
            <!-- <div class="title text-uppercase"> Vehiculos Elim Logística</div> -->
            <!-- <div class="title"> {% if location %} para {{location.direccion}} ({{label}}) {% endif %}</div>  -->
        <!-- </div> -->

        <!-- Card menu -->
        <!-- <div class="alert alert-info"> -->
            <!-- <a class="btn btn-default" onclick="return abrir_modal('{% url 'elim:reg_new' %}')" href="#"> Nuevo servicio</a> -->
            <!-- <a class="btn btn-default" onclick="return abrir_modal('{% url 'elim:vehiculo_new' %}')" href="#"> Nuevo vehiculo</a> -->
            <!-- <a class="btn btn-default" href="{% url 'elim:reg_direccion_new' %}"> Direcciones</a> -->
            <!-- <a class="btn btn-default" href="{% url 'elim:vehiculo_list' %}"> Vehiculos</a>       -->
        <!-- </div> -->
        {% if not obj %}
        <div class="alert alert-info"> Ningun registro disponible </div>
        {% endif %}
        <div class="buttons-toolbar">
            <a class="dropdown-item" href="{% url 'elim:gasto_new' %}">
                <i class="far fa-calendar-plus"></i> 
                Nuevo
            </a>
        </div>

        <table
            id="table"
            data-locale="es-ES"
            data-toggle="table"
            data-toolbar="#toolbar"
            data-search="true"
            data-show-refresh="true"
            data-show-toggle="true"
            data-show-fullscreen="true"
            data-show-columns="true"
            data-show-columns-toggle-all="true"
            data-detail-view="true"
            data-show-export="true"
            data-click-to-select="true"
            data-detail-formatter="detailFormatter"
            data-minimum-count-columns="2"
            data-show-pagination-switch="true"
            data-pagination="true"
            data-id-field="id"
            data-page-list="[10, 25, 50, 100, all]"
            data-show-footer="true"
            data-side-pagination="server"
            data-toolbar=".buttons-toolbar"
        >
            <thead>
                <th data-sortable="true" data-field="fecha">Fecha</th>
                <th data-sortable="true" data-field="origen">Origen</th>
                <th data-sortable="true" data-field="destino">Destino</th>
                <th data-sortable="true" data-field="trayecto">Trayecto</th>
                <th> Distancia </th>
                <th> Duración </th>
                <th> Duracion con tráfico </th>
                <th data-sortable="true" data-field="placa">Placa</th>
                <th data-sortable="true" data-field="conductor">Conductor</th>
                <th data-sortable="true" data-field="vehiculo"> Vehiculo</th>
                <!-- <th>Cantidad</th> -->
                <th data-sortable="true" data-field="efectivo">Efectivo</th>
                <th data-sortable="true" data-field="credito">Crédito</th>
                <th data-sortable="true" data-field="transferencia">Transferencia</th>
                <th data-sortable="true" data-field="total">Total</th>
            </thead>
            <tbody>
                {% for item in obj %}
                <tr>
                    <!-- <td> -->
                        <!-- <a class="btn btn-warning btn-circle" href="{% url 'elim:gasto_edit' item.pk %}"> -->
                            <!-- <i class="far fa-edit"></i> -->
                        <!-- </a> -->
                        <!-- <a href="{{item.imagen.url}}" onclick="return abrir_modal('{% url 'elim:gasto_detail' item.pk %}')">VER</a> -->
                        <!-- <a href="{{item.imagen.url}}" >VER2</a> -->
                    <!-- </td> -->
                    <!-- <td> <a href="{% url 'elim:vehiculo_inactivar' item.pk %}"> 
                            {% if item.estado %} Desactivar {% else %} Activar {% endif %} 
                        </a> 
                    </td> -->
                    <!-- <td> {{item.id}} </td> -->
                    <!-- <td> {{item.fm|date:"d/m/Y H:i:s"}} </td> -->
                    <!-- <td> {{item.hora|date:"H:i:s"}} </td> -->
                    <td> {{item.to_location.fecha|date:"d/m/Y H:i:s"}} </td>
                    <td> {{item.from_location}} </td>
                    <td> {{item.to_location.direccion}} </td>
                    <td> {{item.to_location.trayecto.direccion}} </td>
                    <td> {{item.distance_km_text}}</td>
                    <td> {{item.duration_mins_text}}</td>
                    <td> {{item.duration_traffic_mins_text}}</td>
                    <td> {{item.to_location.placa}} </td>
                    <td> {{item.to_location.placa.conductor}} </td>
                    <td> {{item.to_location.placa.tipo}} </td>
                    <!-- <td> {{item.cantidad}} </td> -->
                    <td> {{item.to_location.efectivo|intcomma}} </td>
                    <td> {{item.to_location.credito|intcomma}} </td>
                    <td> {{item.to_location.transferencia|intcomma}} </td>
                    <td> {{item.to_location.valor|intcomma}} </td>
                    <!-- <td> {{item.placa}} </td> -->
                    <!-- <td> {{item.conductor}} </td> -->
                    <!-- <td>   </td> -->

                    <!-- <div class="embed-responsive embed-responsive-16by9">
                        <iframe class="embed-responsive-item" src="..."></iframe>
                    </div> -->

                    <!-- <td> {{item.mecanico|yesno:"Activo,Inactivo"}} </td> -->
                    <!-- <td> {{item.restaurante|yesno:"Activo,Inactivo"}} </td> -->
                    <!-- <td> {{item.enfermo|yesno:"Activo,Inactivo"}} </td> -->
                    <!-- <td> <a href="{#% url 'elim:geocoding_view' item.id %#}"> Geocode!</a> </td>                        -->
                    <!-- <td><img src="/static/admin/img/icon-no.svg" alt="False"></td> -->

                </tr>
                {% endfor%}
            </tbody>
        </table>        
    </div>
    <div class="linkholder">
        <a class="btn btn-default" href="{% url 'elim:gasto_list' %}"> Registros</a>
        <!-- <a href="{% url 'elim:my_distance_view' %}"> Calcular distancias</a>  -->
    </div>
    <div class="linkholder">
        <!-- <a href="{% url 'elim:my_map_view' %}"> Ir al mapa</a>  -->
    </div>
</div>
{% endblock %}
{% block js_page %}
<script>
</script>
{% endblock %}