api/urls.py
from django.urls import path
from .views import ClienteList, GastoConductorList, GastoConductorAPIList, gastoConductorListReload, gastoConductorList

urlpatterns = [
    path('v1/clientes',ClienteList.as_view(),name='cliente_list'),
    # path('v1/gastos',GastoConductorAPIList.as_view(),name='gastos_list'),
    # path('v1/gastos/reload/view',GastoConductorList.as_view(),name='gastos_list_reload_view'),
    # path('v1/gastos/reload/',gastoConductorList,name='gastos_list_reload'),
    path('v1/gastos/reload/',gastoConductorListReload,name='gastos_list_reload'),
    # path('v1/gastos/reload/(?:fecha=(?P<str:fecha>)/)?$',gastoConductorListReload,name='gastos_list_reload_f'),
    # path('v1/gastos/reload/(?:page-(?P<page_number>[0-9]+)/)?$',gastoConductorListReload,name='gastos_list_reload'),
]

app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('',include(('bases.urls','bases'), namespace='bases')),
    path('elim/',include(('elim.urls','elim'), namespace='elim')),
    path('api/', include(('api.urls', 'api'), namespace='api')),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('admin/', admin.site.urls),
    path('viviana/',include(('viviana.urls','viviana'), namespace='viviana')),
]

urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

elim/urls.py
from rest_framework.routers import DefaultRouter
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

#from .views import *
from . import views
from .reportes import reporte_registros


urlpatterns = [
    path('clientes/',views.ClienteView.as_view(), name='cliente_list'),
    path('clientes/new/',views.ClienteNew.as_view(), name='cliente_new'),
    path('clientes/edit/<int:pk>',views.ClienteEdit.as_view(), name='cliente_edit'),
    path('clientes/inactivar/<int:id>',views.cliente_inactivar, name='cliente_inactivar'),
    path('clientes/delete/<int:pk>',views.ClienteDel.as_view(), name='cliente_del'),

    path('vehiculos/',views.VehiculoView.as_view(), name='vehiculo_list'),
    path('vehiculos/new/',views.VehiculoNew.as_view(), name='vehiculo_new'),
    path('vehiculos/edit/<str:pk>',views.VehiculoEdit.as_view(), name='vehiculo_edit'),
    path('vehiculos/inactivar/<str:pk>',views.vehiculo_inactivar, name='vehiculo_inactivar'),


    path('proveedores/',views.ProveedorView.as_view(), name='proveedor_list'),
    path('proveedores/new',views.ProveedorNew.as_view(), name='proveedor_new'),
    path('proveedores/edit/<int:pk>',views.ProveedorEdit.as_view(), name='proveedor_edit'),
    path('proveedores/delete/<int:pk>',views.ProveedorDel.as_view(), name='proveedor_del'),
    
    path('conductor/',views.ConductorView.as_view(), name='conductor_view'),
    path('conductor/edit/<str:pk>',views.ConductorEdit.as_view(), name='conductor_edit'),
    
    # path('servicios/',ServicioView.as_view(), name='servicio_list'),
    # path('servicios/new',ServicioNew.as_view(), name='servicio_new'),
    # path('servicios/edit/<int:pk>',ServicioEdit.as_view(), name='servicio_edit'),
    # path('servicios/delete/<int:pk>',ServicioDel.as_view(), name='servicio_del'),

    # path('servicios/o',servicio_new, name='servicio_def'),

    # path('servicios/u',MuseoCreateView.as_view(), name='museo-add'),


    path('registros/',views.RegistroView.as_view(), name='reg_list'),
    # path('registros/new',views.RegistroNew.as_view(), name='reg_new'),
    # path('registros/edit/<int:pk>',views.RegistroEdit.as_view(), name='reg_edit'),
    path('registros/new',views.reg_add_edit, name='reg_new'),
    path('registros/edit/<int:id>',views.reg_add_edit, name='reg_edit'),
    # path('registros/inactivar/<int:id>',views.cliente_inactivar, name="cliente_inactivar"),

    path('registros/lista/direccion/',views.TrayectoView.as_view(), name='reg_direccion_new'),
    path('registros/direccion/new/',views.TrayectoNew.as_view(), name='reg_direccion_add_new'),

    path('prueba/', views.index, name="index"),
    path('js', views.index_js, name="index-js"),
    path('localizacion', views.localizacion, name="local"),
    
    
    path('trayectos/', views.HomeTrayectosView.as_view(), name='trayecto_view'), 
    path('trayectos/<int:pk>', views.ActInaTrayectoView.as_view(), name='actina_view'), 
    path('rutas/', views.rutas, name="route"),
    path('geocoding/<int:pk>', views.GeocodingView.as_view(), name='geocoding_view'),     
    path('distance', views.DistanceView.as_view(), name='my_distance_view'), 
    

    path('gastos/',views.GastoConductorView.as_view(), name='gasto_list'),
    # path('gastos/',views.gastoConductorView, name='gasto_list'),
    path('gastos/new/',views.GastoConductorNew.as_view(), name='gasto_new'),
    path('gastos/edit/<int:pk>',views.GastoConductorEdit.as_view(), name='gasto_edit'),
    path('gastos/detail/<int:pk>',views.GastoConductorDetailView.as_view(), name='gasto_detail'),
    
    path('map/', views.MapView.as_view(), name='my_map_view'), 
    path('map/conductor/', views.MapConductorView.as_view(), name='conductor_map_view'), 
    path('route/', views.route, name="route"),

    path('reporte/', reporte_registros, name='registros_print_all'),
    
    path('reporte/list/',views.ReporteView.as_view(), name='repo_list'),    
    path('reporte/detail/<int:pk>',views.ReporteDetailView.as_view(), name='repo_detail'),
    
    path('conductor/viaje/reporte/list/',views.ViajeView.as_view(), name='repo_viaje_list'),    
    path('conductor/viaje/reporte/detail/<int:pk>',views.ViajeDetailView.as_view(), name='repo_viaje_detail'),
    
    path('status/',views.StatusDetailView.as_view(), name='status_list'),
    path('status/<str:pk>/',views.vehiculo_activar_inactivar, name='status_activarinact_list'),
    # path('status/<str:pk>/(?:page(?P<page_number>[0-9]+)/)?$',views.vehiculo_activar_inactivar, name='status_activarinact_list'),
    path('status/mecanico/<str:pk>/',views.vehiculo_cambiar_mecanico, name='status_cambiar_mecanico_list'),
    path('status/restaurante/<str:pk>/',views.vehiculo_cambiar_restaurante, name='status_cambiar_restaurante_list'),
    path('status/enfermo/<str:pk>/',views.vehiculo_cambiar_enfermo, name='status_cambiar_enfermo_list'),
    path('status/color/<str:pk>/',views.vehiculo_status_disponibilidad, name='status_cambiar_color_list'),
    path('status/edit/<str:pk>/',views.StatusEdit.as_view(), name='status_edit'),
    
    path('panel/',views.panelView, name='panel_view'),
]


router = DefaultRouter()
router.register("api/paises", views.PaisesViewSet, basename="paises")
router.register("api/museos", views.MuseoViewSet, basename="museos_list")
router.register("api/clientes", views.ClientesViewSet, basename="clientes")
router.register("v1/clientes/", views.ClientesViewSet, basename="clientes_list")
# router.register("v1/gastos", views.GastoConductorViewSet, basename="gastos__list")

urlpatterns += router.urls
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

elim/models.py
from django.core.validators import MaxValueValidator, MinValueValidator
# from django.core.exceptions import ValidationError
from django.contrib.auth.models import User
from django.db import models
from django.utils.translation import gettext_lazy as _
from django_userforeignkey.models.fields import UserForeignKey
import uuid
from bases.models import ClaseModelo, ClaseModelo2

# Trayecto models.
class Trayecto(ClaseModelo):
    
    direccion = models.CharField(verbose_name='Dirección',max_length=200)    
    zipcode = models.CharField(verbose_name='Código postal',max_length=6)
    ciudad = models.CharField(verbose_name='Ciudad',max_length=200,blank=True, null=True)
    pais = models.CharField(verbose_name='Pais',max_length=200,blank=True, null=True)
    lat = models.CharField(verbose_name='Latitud',max_length=200,blank=True, null=True)
    lng = models.CharField(verbose_name='Longitud',max_length=200,blank=True, null=True)
    club = models.CharField(verbose_name='Club',max_length=500,blank=True, null=True)    
    place_id = models.CharField(max_length=200,blank=True, null=True)

    def __str__(self):
        return f'{self.direccion}'
    
    def save(self):
        super(Trayecto,self).save()

    class Meta:
        verbose_name_plural = 'Trayectos'

# Create your models here.

class Persona(ClaseModelo):
    nombre = models.CharField(max_length=50,help_text= "Nombre de la persona")
    celular = models.CharField(max_length=10,help_text= "Número de celular")
    
    def __str__(self):
        return f'{self.nombre}'
    
    def save(self):
        super(Persona,self).save()

    class Meta:
        verbose_name_plural = 'Personas'

class Cliente(ClaseModelo):
    nombre = models.CharField(max_length=50,help_text= "Nombre del cliente")
    
    def __str__(self):
        return f'{self.nombre}'
    
    def save(self):
        super(Cliente,self).save()

    class Meta:
        ordering = ['nombre']
        verbose_name_plural = 'Clientes'


class Proveedor(ClaseModelo):
    nombre = models.CharField(max_length=50,help_text= "Nombre del proveedor")
    
    def __str__(self):
        return '{}'.format(self.nombre)
    
    def save(self):
        super(Proveedor,self).save()

    class Meta:
        verbose_name_plural = 'Proveedores'

class Conductor(ClaseModelo):
    cedula = models.BigIntegerField(help_text= "Cédula",blank=True,null=True)
    nombre = models.CharField(max_length=50,help_text= "Nombre del conductor")

    def __str__(self):
        # return '{}'.format(self.nombre)
        return f'{self.nombre}'
    
    def save(self):
        super(Conductor,self).save()

    class Meta:
        ordering = ['nombre']
        verbose_name_plural = 'Conductores'

class Vehiculo(ClaseModelo):
    
    class Disponibilidad(models.TextChoices):
        INACTIVO = "INACTIVO", _("Inactivo")
        ACTIVO = "ACTIVO", _("Activo")
        VERDE = "VERDE", _("Verde")
        ROJO = "ROJO", _("Rojo")
    
    class Tipo(models.TextChoices):
        VAN = "VAN", _("Van")
        ESTACAS = "ESTACAS", _("Estacas")
        MINIVAN = "MINIVAN", _("Minivan")
        CAMION = "CAMION", _("Camion")
    
    tipo = models.CharField(max_length=10,choices=Tipo,default=Tipo.VAN)
    placa = models.CharField(primary_key = True,max_length=6)    
    conductor = models.ForeignKey(Conductor,on_delete=models.PROTECT,max_length=50)    
    hora = models.DateTimeField()
    disponibilidad = models.CharField(max_length=10,choices=Disponibilidad,default=Disponibilidad.INACTIVO)
    mecanico = models.BooleanField(default=False,blank=True, null=True)
    restaurante = models.BooleanField(default=False,blank=True, null=True)
    enfermo = models.BooleanField(default=False,blank=True, null=True)
    ubicacion = models.ForeignKey(Trayecto,on_delete=models.RESTRICT,blank=True, null=True)


    def is_upperclass(self):
        return self.disponibilidad in {
            self.Disponibilidad.ACTIVO,
            self.Disponibilidad.INACTIVO,
        }

    def __str__(self):
        return self.placa
    
    def save(self):
        self.placa = self.placa.upper()
        super(Vehiculo,self).save()

    class Meta:
        verbose_name_plural = 'Vehiculos'


class Programador(ClaseModelo):
    nombre = models.CharField(max_length=50,help_text= "Nombre del programador")

    def __str__(self):
        return '{}'.format(self.nombre)
    
    def save(self):
        super(Programador,self).save()

    class Meta:
        verbose_name_plural = 'Programadores'


class Servicio(ClaseModelo):
    
    class Medio_pago(models.TextChoices):
        CONTADO = "CONTADO", _("Contado")
        CREDITO = "CREDITO", _("Crédito")
        TRANSFERENCIA = "TRANSFERENCIA", _("Transferencia")

    class Status(models.TextChoices):
        Creado = "creado", _("Creado")        
        Ejecutado = "ejecutado", _("Ejecutado")
        Cotizado = "cotizado", _("Cotizado")
        Facturado = "facturado", _("Facturado")
        no_show = "no_show", _("NO SHOW")
    
    class Legalizado(models.TextChoices):        
        sin_legalizar = "sin legalizar", _("Sin legalizar")
        Legalizado = "legalizado", _("Legalizado")

    fecha = models.DateTimeField(null=True,blank=True)
    numero_registo = models.UUIDField(default=uuid.uuid4,max_length=80)
    cliente	 = models.ForeignKey(Cliente,on_delete=models.CASCADE,max_length=50,)
    placa = models.ForeignKey(Vehiculo,on_delete=models.CASCADE,)
    medio_pago = models.CharField(verbose_name='Medio de peago',max_length=15,choices=Medio_pago,default=Medio_pago.CONTADO,)
    valor = models.DecimalField(max_digits=9, decimal_places=2,default=0.0)
    trayecto = models.ForeignKey(Trayecto,on_delete=models.CASCADE,max_length=50,)
    solicitado_por = models.ForeignKey(Persona,on_delete=models.CASCADE,)
    celular = models.CharField(max_length=10,)
    programador = models.ForeignKey(Programador,on_delete=models.CASCADE,)
    costo = models.DecimalField(max_digits=9, decimal_places=2 ,default=0.0)
    neto = models.DecimalField(max_digits=9, decimal_places=2,default=0.0)
    status = models.CharField(max_length=15,choices=Status,default=Status.Creado,help_text= "Status")
    cotizacion = models.DecimalField(max_digits=9, decimal_places=2,default=0,blank=True)
    factura = models.CharField(blank=True,max_length=50,help_text= "Factura")
    legalizado = models.CharField(max_length=15,choices=Legalizado,default=Legalizado.sin_legalizar,help_text= "Legalizado")
    
    def __str__(self):
        return f'{self.placa}'
        # return '{}'.format(self.placa)
    
    def save(self):
        super(Servicio,self).save()

    class Meta:
        verbose_name_plural = 'Servicios'
        #unique_together = ('fecha','cliente','cliente','medio_pago','valor','trayecto')


class Pais(models.Model):
    nombre = models.CharField('Nombre Pais',max_length=50)
    class Meta:
        verbose_name = 'Pais'
        verbose_name_plural = 'Paises'
    
    def __str__(self):
        return self.nombre


class Museo(models.Model):
    nombre = models.CharField('Nombre Museo',max_length=80)
    pais = models.ForeignKey('Pais',on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'Museo'
        verbose_name_plural = 'Museos'
    
    def __str__(self):
        return self.nombre

class Parametro(ClaseModelo2):      
    nombre = models.CharField(max_length=200,null=False,blank=False)
    valor = models.DecimalField(max_digits=9, decimal_places=2)
    
    def __str__(self):
        return f'{self.nombre}={self.valor} '

    class Meta:
        verbose_name_plural = 'Parametros'
class Medio_pago(models.TextChoices):
        CONTADO = "CONTADO", _("Contado")
        CREDITO = "CREDITO", _("Crédito")
        TRANSFERENCIA = "TRANSFERENCIA", _("Transferencia")
        CHIP = "CHIP", _("Chip")

class Registro(ClaseModelo):    
    numero_registo = models.UUIDField(default=uuid.uuid4,max_length=80)    
    fecha = models.DateTimeField(null=True,blank=True)
    direccion = models.CharField(max_length=200,null=False,blank=False)
    latitud = models.CharField(max_length=200,null=True,blank=True)
    longitud = models.CharField(max_length=200,null=True,blank=True)
    trayecto = models.ForeignKey(Trayecto,on_delete=models.PROTECT)
    cliente	= models.ForeignKey(Cliente,on_delete=models.PROTECT)    
    placa = models.ForeignKey(Vehiculo,on_delete=models.PROTECT)    
    solicitado_por = models.ForeignKey(Persona,on_delete=models.PROTECT)
    celular = models.CharField(max_length=10)
    medio_pago = models.CharField(max_length=15,choices=Medio_pago,default=Medio_pago.CONTADO)
    valor = models.DecimalField(max_digits=9, decimal_places=2, default=0.0)
    costo = models.DecimalField(max_digits=9, decimal_places=2, default=0.0,blank=True)
    neto = models.DecimalField(max_digits=9, decimal_places=2, default=0.0,blank=True)
    efectivo = models.DecimalField(max_digits=9, decimal_places=2,default=0.0,blank=True)
    credito = models.DecimalField(max_digits=9, decimal_places=2,default=0.0,blank=True)
    transferencia = models.DecimalField(max_digits=9, decimal_places=2,default=0.0,blank=True)
    porcentaje = models.DecimalField(max_digits=9, decimal_places=2,default=0.0,blank=True)
    def __str__(self):
        return f"{self.direccion}, {self.placa}"        
        # return "%s %s" % (self.direccion, self.placa)        
        # return f'{self.placa}'
        # return '{}'.format(self.placa)
    
    def save(self):        
        self.porcentaje = Parametro.objects.get(pk=1).valor
        self.costo = float(self.valor) * float(self.porcentaje) or 0.25
        self.neto = float(self.valor) - float(self.costo)
        if self.medio_pago == Medio_pago.CONTADO:
            self.credito = float(0)
            self.transferencia = float(0)
            self.efectivo = float(self.valor)
        elif self.medio_pago == Medio_pago.CREDITO:
            self.credito = float(self.valor)
            self.transferencia = float(0)

elim/templates/gastos/gasto_detail.html
{% load static %}
<div class="modal-dialog modal-xl">
    <div class="modal-content">
        <div class="modal-header">
            <h4 class="modal-title">Factura gasto, {{obj.conductor}} <span> </span></h4>
            <button type="button" class="close" onclick="return cerrar_modal()">&times;</button>
        </div>

        <div class="modal-body">
            <picture>
                <source srcset="{{obj.imagen.url}}" type="image/svg+xml">
                <img src="{{obj.imagen.url}}" class="img-fluid" alt="{{obj.imagen.name}}">
            </picture>
        </div>
        <div class="modal-footer">
            <button onclick="return cerrar_modal()" type="button" class="btn btn-success"
                data-dismiss="modal">Cerrrar</button>
        </div>
    </div>
</div>


{% block js_page %}


<script>
    $(function () {
    });
</script>

{% endblock %}

elim/templates/gastos/gasto_form.html
{% extends 'base/base.html' %}

{% block page_content %}
<div class="panel-body">
    <div>
        {% if obj.pk  %}
        <form method="POST" role="form" id="frm" class="form-inline" action="{% url 'elim:gasto_edit' obj.pk %}" enctype="multipart/form-data">
        {% else %}
        <form method="POST" role="form" id="frm" class="form-inline" action="{% url 'elim:gasto_new' %}" enctype="multipart/form-data">
        {% endif %}
            <div class="col-xl-12 col-md-12 mb-12">
                {% if obj.pk %}
                <div class="card border-left-warning shadow h-100 py-2">
                {% else %}
                <div class="card border-left-success shadow h-100 py-2">
                {% endif %}
                    <div class="card-body">
                        <div class="row no-gutters align-items-center">
                            <div class="col mr-2">
                                <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                                    {% if obj.pk %} Editar gasto del conductor {% endif %}
                                </div>                                
                                {% csrf_token %}
                                <small class="text-danger">
                                    {% if form.errors %}
                                        {% for field in form %}
                                            {% if field.errors %}
                                                {% for error in field.errors %}
                                                    {{ error|escape }}
                                                {% endfor %}
                                            {% endif %}
                                        {% endfor %}
                                    
                                        {% if form.non_field_errors%}
                                            {% for error in form.non_field_errors %}
                                                {{ error|escape }}
                                            {% endfor %}
                                        {% endif %}
                                    {% endif %}
                                </small>
                                <div class="dropdown-divider"></div>
                                {{form.fecha.label}}
                                {{form.fecha}}                                
                                {{form.factura.label}}
                                {{form.factura}}
                                <br>
                                {{form.valor.label}}
                                {{form.valor}} 
                                {{form.medio_pago}}
                                {{form.concepto}}
                                <br>
                                {{form.descripcion.label}}
                                {{form.descripcion}}
                                <br>
                                {{form.imagen.label}}
                                {{form.imagen}}
                                <br>
                                
                                <label for="id_estado_aceptacion" id="id_estado_label" class="form-control"> Aceptar o rechazar</label>
                                {{form.estado_aceptacion}}

                                <label for="id_vehiculo" id="id_vehiculo_label" class="form-control"> Vehiculo</label>
                                
                                <!-- {#% if request.user.is_superuser %#}                             -->
                                    
                                    {{form.vehiculo}}                                   
                                <!-- {#% endif %#} -->
                                
                                <div class="dropdown-divider"></div>
                                <div class="row">
                                    <div class="col">
                                        <button type="submit" class="btn btn-danger">
                                            <span class="fa fa-save"></span> 
                                            Guardar
                                        </button>
                                        <a type="button" class="btn btn-success" href="{% url 'elim:gasto_list' %}">
                                            Cancelar
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>

{% endblock %}

{% block js_page %}
<script>
    $(function () {
        $("#sidebarToggle").click();  
        $("#id_vehiculo").val("{{ obj.vehiculo.placa }}").change();
        // $("#id_fecha").val("{{ obj.fecha|date:'d/m/Y' }}");

        if ("{{request.user.is_superuser}}" === "False"){            
            $("#id_estado_aceptacion").attr({hidden: true});
            $("#id_estado_label").attr({hidden: true});
            // $('#id_vehiculo option').attr('disabled', 'disabled');
            $('#id_vehiculo_label').hide();
            $('#id_vehiculo').hide();
        }
    });

    $("#id_fecha").datetimepicker({
        format: 'd/m/Y H:i:s',
        timepicker:true ,
        // defaultDate:new Date(),
        // minDate: 0, /** AAAA,MM,DD Fecha inicio */
        // maxDate: new Date( new Date().getFullYear(), 12, 31),
    });  
</script>

{% endblock %}

elim/templates/gastos/gasto_list copy.html
{% extends 'base/base.html' %}
{% block page_content %}
{% load humanize %}
<div class="card shadow mb-4">
    <!-- Card Header - Dropdown -->
    <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
        <h6 class="m-0 font-weight-bold text-primary">Gastos del vehiculo</h6>
        <div class="dropdown no-arrow">
            <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown"
                aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
            </a>
            <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in" aria-labelledby="dropdownMenuLink">
                <div class="dropdown-header">Acciones:</div>
                <a class="dropdown-item" href="{% url 'elim:gasto_new' %}">
                    <i class="far fa-calendar-plus"></i> Nuevo</a>
            </div>
        </div>
    </div>
    <!-- Card Body -->
    <div class="card-body">
        <div class="titleholder">
            <!-- <div class="title text-uppercase"> Vehiculos Elim Logística</div> -->
            <!-- <div class="title"> {% if location %} para {{location.direccion}} ({{label}}) {% endif %}</div>  -->
        </div>

        <!-- Card menu -->
        <div class="alert alert-info">
            <a class="btn btn-default" href="{% url 'elim:gasto_new' %}" > Registrar gasto </a>
            <!-- <a class="btn btn-default" onclick="return abrir_modal('{% url 'elim:reg_new' %}')" href="#"> Nuevo servicio</a> -->
            <!-- <a class="btn btn-default" onclick="return abrir_modal('{% url 'elim:vehiculo_new' %}')" href="#"> Nuevo vehiculo</a> -->
            <!-- <a class="btn btn-default" href="{% url 'elim:reg_direccion_new' %}"> Direcciones</a> -->
            <!-- <a class="btn btn-default" href="{% url 'elim:vehiculo_list' %}"> Vehiculos</a>       -->
        </div>
        {% if not obj %}
        <div class="alert alert-info"> Ningun gasto conductor disponible </div>
        {% endif %}
        <table class="table table-striped table-hover dt-responsive nowrap">
            <thead>
                <th class="all"> Acciones</th>                
                <th>Estado</th>
                <!-- <th>fecha</th> -->
                <th>Concepto</th>
                <th>Medio de pago</th>
                <th>N° Factura</th>
                <th>Total</th>
                <th>Efectivo</th>
                <th>Crédito</th>
                <th>Transferencia</th>
                <th>Descripción</th>
            </thead>
            <tbody>
                {% for item in obj %}
                <tr>
                    <td>
                
                    </td>
                    <!-- <td> {{item.estado_aceptacion|yesno:"Aceptado,Rechazado"}} </td> -->
                    <td> {% if item.estado_aceptacion and item.usuario_aceptacion %} Aceptado {% elif item.usuario_rechazo %} Rechazado {% endif %}  </td>
                    <!-- <td> <a href="{% url 'elim:vehiculo_inactivar' item.pk %}"> 
                            {% if item.estado %} Desactivar {% else %} Activar {% endif %} 
                        </a> 
                    </td> -->
                    <!-- <td> {{item.id}} </td> -->
                    <!-- <td> {{item.fm|date:"d/m/Y H:i:s"}} </td> -->
                    <!-- <td> {{item.hora|date:"H:i:s"}} </td> -->
                    <!-- <td> {{item.fecha|date:"d/m/Y H:i:s"}} </td> -->
                    <td> {{item.concepto}} </td>
                    <td> {{item.medio_pago}} </td>
                    <td> {{item.factura}} </td>
                    <td> {{item.valor |intcomma }} </td>
                    <td> {{item.efectivo|intcomma}} </td>
                    <td> {{item.credito|intcomma}} </td>
                    <td> {{item.transferencia|intcomma}}  </td>
                    <td> {{item.descripcion}}  </td>
                </tr>
                {% endfor%}
            </tbody>
        </table>        
    </div>
</div>

<!-- <a class="btn btn-warning btn-circle" href="{#% url 'elim:gasto_edit' item.pk %#}"> -->
    <!-- <i class="far fa-edit"></i> -->
<!-- </a> -->
<!-- <a href="{#{item.imagen.url}#}" onclick="return abrir_modal('{#% url 'elim:gasto_detail' item.pk %#}')">VER</a> -->
<!-- <a href="{{item.imagen.url}}" >VER2</a> -->

{% endblock %}
{% block js_page %}
<script>
    // Call the dataTables jQuery plugin
    $(document).ready(function () {
        $("#sidebarToggle").click();
        $('.table').DataTable({
            processing : true,
            serverSide : true,
            defe
        });
    });
</script>
{% endblock %}

elim/templates/gastos/gasto_view.html
{% extends 'base/base.html' %}
{% block page_content %}
  <h1>Registrar dirección</h1>
  <form method="post">
    {% csrf_token %}
    {{form.as_div}}
    <button type="submit" class="btn-outline-primary">Registrar</button>
  </form>
{% endblock page_content %}